[rule]
description = """
Identifies attempts to load an unsigned and untrusted module by a SYSTEM process. This may indicate an attempt to
elevate privileges via DLL search order hijacking.
"""
id = "39224ead-14f3-4df3-b6ed-ec69dc17db3a"
license = "Elastic License v2"
name = "Untrusted DLL Loaded by a System Windows Process"
os_list = ["windows"]
version = "1.0.1"

query = '''
library where 
  process.code_signature.subject_name : "Microsoft *" and dll.hash.sha256 != null and 
  user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20") and not dll.code_signature.status : "trusted" and 
  dll.Ext.relative_file_creation_time <= 500 and 
  /* svchost covered by fce4b49f-59ff-464e-a69b-e3b38841b5fe */
  not process.name : ("rundll32.exe", "regsvr32.exe", "powershell.exe", "msiexec.exe", "svchost.exe", "w3wp.exe") and
  not dll.path : ("?:\\Windows\\system32\\*", 
                  "?:\\Windows\\syswow64\\*",
                  "?:\\Program Files (x86)\\*",
                  "?:\\Program Files\\*",
                  "?:\\Windows\\Installer\\*",
                  "?:\\Windows\\SystemTemp\\*",
                  "?:\\Windows\\SoftwareDistribution\\*",
                  "?:\\Windows\\WinSxS\\*",
                  "?:\\Windows\\assembly\\*") and
  process.executable :
               ("?:\\Windows\\system32\\*",
                "?:\\Windows\\syswow64\\*",
                "?:\\Program Files (x86)\\Microsoft\\*",
                "?:\\Program Files\\Microsoft\\*", 
                "?:\\Program Files\\Windows *", 
                "?:\\Program Files (x86)\\Windows *", 
                "?:\\Program Files\\Common Files\\Microsoft*",
                "?:\\Program Files (x86)\\Common Files\\Microsoft*") and
  not dll.hash.sha256 : "bf14ce30695de66d8040cb893ba72fb205add0404091cc889e5b4d18b368303b"
'''

min_endpoint_version = "8.10.0"
reputation = true
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1574"
name = "Hijack Execution Flow"
reference = "https://attack.mitre.org/techniques/T1574/"
[[threat.technique.subtechnique]]
id = "T1574.001"
name = "DLL Search Order Hijacking"
reference = "https://attack.mitre.org/techniques/T1574/001/"



[threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

[internal]
min_endpoint_version = "8.10.0"
